source "https://rubygems.org"

# Use the GitHub Pages gem for compatibility
gem "github-pages", group: :jekyll_plugins

# Default theme for new Jekyll sites
gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end
